### ISSUE TITLE
入力フォームの案内がどこにあるのか不明

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/as_info#124]
ここに書いてあるくらいか？
https://github.com/waic/as_test/wiki/AS%E6%83%85%E5%A0%B1%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88%E5%AE%9F%E6%96%BD%E6%96%B9%E6%B3%95

**Comment by nishimotz** [comment]
#129 でカバーします
