### ISSUE TITLE
ASテスト結果の常時受付

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/as_info#129]
- Googleフォームによる1件ずつの入力
- Googleスプレッドシートによる一括入力？

今までは、スプレッドシートは個人向けのシートを作成していたが、不特定多数向けには用意できないのでは？
セキュリティ的にも他人の入力結果が見えるのは良くないのでは？

**Comment by nishimotz** [comment]
提出手段のひとつとして、こういうのはどうでしょか。

* GoogleスプレッドシートのURLを入力してもらう Google フォームを作る
* 読み取り専用の雛形スプレッドシートを作って「コピーして使ってください」と告知する
* 報告者は雛形スプレッドシートをコピーして結果を複数入力して、そのURLを報告する

**Comment by nishimotz** [comment]
これで行くとしたらやること

* 雛形スプレッドシートの作成
* スプレッドシートのURLを入れてもらうフォームの作成
* 報告者に手順を説明するドキュメントの整備

**Comment by nishimotz** [comment]
* もくもく会用の雛形：UAやOSなどの選択肢をメンテすれば使える
* URL入力フォーム作成 @nishimotz
* [報告者向けドキュメント](https://github.com/waic/as_test/wiki/AS%E6%83%85%E5%A0%B1%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88%E5%AE%9F%E6%96%BD%E6%96%B9%E6%B3%95) をメンテする
* 手順をレビューする
* 入力フォームへのリンクを waic.jp にお願いする

**Comment by SawadaStdDesign** [comment]
ようやく雛形スプレッドシートを作っているわけですが...
https://docs.google.com/spreadsheets/d/1gQu1aIpZGl1hcllYEz_ylRcrtAsCAW26wRUuWfB2suU/edit#gid=1222077629

常時受付にするということは、OS／ブラウザ／支援技術の各バージョンを細かく指定したプルダウンの用意って無理じゃないかと思いました。
ので、ラベルに「バージョンは（警告を気にせず）手入力してください」という文言を追加し、プルダウンの内容からバージョン表記を削除しました。

**Comment by SawadaStdDesign** [comment]
もしかして、期待される結果は10まで増やさないといけないということですな。

**Comment by nishimotz** [comment]
URL入力フォーム予定地
https://forms.gle/x2MDRESCqbkyyBej7

**Comment by nishimotz** [comment]
スプレッドシートのコピーをどこに作成してもらって、どういう共有設定にしてもらうか、説明が必要

**Comment by nishimotz** [comment]
* フォーム「報告者向けドキュメント」にリンクする
* 「報告者向けドキュメント」をメンテする
* https://waic.jp/guideline/as/ からリンクされた「AS情報の作成」（説明ページ）  @SawadaStdDesign が原稿を書く

**Comment by nishimotz** [comment]
[報告者向けドキュメント](https://github.com/waic/as_test/wiki/AS%E6%83%85%E5%A0%B1%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88%E5%AE%9F%E6%96%BD%E6%96%B9%E6%B3%95)

「4 テスト結果の入力」の説明を更新しました。下記の記述をどうするか？

（ここから）

メールによるテスト結果の送信については以下をご確認ください。
[テスト結果をメールでお送りいただく場合について](https://waic.jp/news/20181226/#report_by_email)

（ここまで）

**Comment by nishimotz** [comment]
「Google スプレッドシートも Google フォームも使えない」場合を、「メールによるテスト結果の送信」でカバーする。

現状「メールによるテスト結果の送信」はWikiページから2018年の記事へのリンクになっている。

TODO : waic.jp Web 管理者に確認する。

**Comment by nishimotz** [comment]
幹事会のフィードバック

* 「メールによるテスト結果の送信」は contact 宛メールでよいのでは
* スプレッドシートで入力してフォームを送信した報告者が、その後、同じシートの内容を更新したり追記した場合に、受理した側は把握できるのか？フォーム送信時点での内容を受理する、新しい情報の報告には過去のシートを再利用しない、などの注記が必要ではないか？

**Comment by nishimotz** [comment]
「記入されたシートはフォーム送信時点での内容を受理します。」をWikiページに追記しました。

> * フォーム「報告者向けドキュメント」にリンクする
> * 「報告者向けドキュメント」をメンテする
> * https://waic.jp/guideline/as/ からリンクされた「AS情報の作成」（説明ページ）  @SawadaStdDesign が原稿を書く

実はページを新たに作る必要がなさそう。

やること

(1)

https://waic.jp/guideline/as/

「意義」の直後に

> 検証作業に対するご協力のお願い
> アクセシビリティ サポーテッド情報を作成するために必要な検証作業は、どなたでも参加可能で、いつでも実施することができます。
> 
> 参加方法

https://github.com/waic/as_test/wiki/AS%E6%83%85%E5%A0%B1%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88%E5%AE%9F%E6%96%BD%E6%96%B9%E6%B3%95

に遷移するリンクを付けてもらう。

(2)

ニュースページの原稿を @SawadaStdDesign さんが作る。

Web担当者に提供する。

**Comment by nishimotz** [comment]
告知されました
https://waic.jp/news/20230801/
