### ISSUE TITLE
AS情報トップ（/guideline/as/）｢アクセシビリティ・サポーテッド検証結果｣要否検討

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/as_info#2]
｢アクセシビリティ・サポーテッド検証結果｣ を公開し続けるのかどうか要検討
→ 公開するなら「過去の」を追加？
→ 「アクセシビリティ・サポーテッド（AS）情報HTML形式」のみでよいのでは？

**Comment by Morokuma0406** [comment]
過去の足跡がわかる、という観点で、「過去の資料」としてわかるようにすることを前提に残すべきだと思います。

**Comment by SawadaStdDesign** [comment]
稀に歴史が知りたいこともあるので。

**Comment by SawadaStdDesign** [comment]
「過去のアクセシビリティ サポーテッド検証結果」として残し、公開済みのためcloseします。
