### ISSUE TITLE
AS情報トップ（/guideline/as/）検証結果のライセンス

### ISSUE THREAD

**Issue by SawadaStdDesign** [waic/as_info#3]
「アクセシビリティ・サポーテッド検証結果」のライセンスについて
→ 過去のデータに対するライセンス表示の要否
→ 最新のデータに対するライセンス表示の要否

**Comment by SawadaStdDesign** [comment]
過去の検証結果に関しては、ライセンス表記をすることを条件に作業をお願いした経緯があるため残す。

**Comment by SawadaStdDesign** [comment]
最新（2018/12〜2019/01）については、テストをお願いした時点で表明していなかったため、表記しない。

**Comment by SawadaStdDesign** [comment]
ここでの「ライセンス」は「各ドキュメントの原著作者一覧」を指しており、二次利用に関しての議論ではない。

**Comment by SawadaStdDesign** [comment]
クリエイティブ・コモンズ・ライセンスにするのかどうか？
大幅に変える必要はないので、そのままでよいのでは。
TEST-CODEのmetaには「CC BY-SA 2.1 JP」を入れてある。

**Comment by SawadaStdDesign** [comment]
CC 2.1から4.0に更新する必要あり？

**Comment by nishimotz** [comment]
4.0 でもよいかもと最初から指摘していただいていた話
https://github.com/waic/as_test/issues/70

**Comment by nishimotz** [comment]
guideline-as-20200318.html の更新を確認していますが、AS 情報の各ページも
「表示 - 継承 4.0 国際」
に変更すればよいでしょうか？

現状は「表示 - 継承 4.0 日本」ですが、リンク先は「国際」になっています。
https://creativecommons.org/licenses/by-sa/4.0/deed.ja

**Comment by SawadaStdDesign** [comment]
そうですね。「国際」でいきましょう。

**Comment by SawadaStdDesign** [comment]
過去のデータに対するライセンスと最新のデータに対するライセンスを分けて表示することで決定。
また、テスト実施者に個別に確認し、公開することに問題ないとの結果だったため、公開済み。
closeします。
