### ISSUE TITLE
AS情報 個別ページのリンクテキストについて

### ISSUE THREAD

**Issue by momdo** [waic/as_info#93]
ex https://as-info-next.herokuapp.com/results/0010-05.html

> テストの対象となる達成基準
1.3.1 情報及び関係性 (レベルA)
> 
> 関連する達成方法
H51: 表形式の情報を提示するために、テーブルのマークアップを使用する

とありますが、

- 「1.3.1 情報及び関係性 (レベルA)」は、WCAGの達成基準や解説書へのリンク
- 「H51: 表形式の情報を提示するために、テーブルのマークアップを使用する」は、達成方法へのリンク

のようにそれぞれ見えます（実際にはそうではありません）。

リンクテキストについて検討いただけると嬉しいです。

**Comment by bakera** [comment]
「1.3.1 情報及び関係性 (レベルA) に関連するAS情報」みたいなラベルにすると良いのですかね?

**Comment by cocktailz** [comment]
「検証結果を含む達成基準」
「検証結果を含む達成方法」
「など直前に見出しがあって、それと併せることでリンク先を予測できるような気もします。

**Comment by nishimotz** [comment]
とにかく各リンクに「に関連するAS情報」をつけてみました。

見出しを増やす件は具体的な作業がわからないので未着手です。

下手にいじると、リンク先の各ページのタイトルや見出しも、
整合するように手直しが必要な気がします。

**Comment by SawadaStdDesign** [comment]
0010-05.htmlページ上での目的は、あくまで
「このテストケースの対象となる達成基準／このテストケースが関連する達成方法 を紹介する」
ですので、伊敷さんの「「検証結果を含む〜」という見出しにする（or 追加する）」案はちょっとズレる気がします。

で、太田さんの「リンクテキストに「〜に関連するAS情報」を追加する」案は、遷移した先のページのh1には「アクセシビリティ サポーテッド（AS）情報：〜」を含んでいますので、西本さんが心配されてる整合性に問題はないと思います。

リンクテキストを遷移した先のページのh1に近づけるとすると、

- AS情報：1.3.1 情報及び関係性 (レベルA)
- AS情報：H51: 表形式の情報を提示するために、テーブルのマークアップを使用する

とかでしょうか？
先頭に持ってきた方が違いが明確になるような気がします。
（「：」がダブりますけど

**Comment by bakera** [comment]
よく見ると直前の見出しは
「テストの対象となる達成基準」
なので、このリンク先で達成基準が見られるものと期待しそうですね。
いっそ両方載せるとか?

```
テストの対象となる達成基準
- 1.3.1 情報及び関係性 (レベルA) 
- 1.3.1 情報及び関係性 (レベルA) に関連するAS情報
```

**Comment by SawadaStdDesign** [comment]
> いっそ両方載せるとか?

これ以上本来のコンテンツよりも上に関連リンクを増やすことは避けたい気持ちがあります。
今回は情報設計までやり直しておらず、西本さんに勢いで作っていただいた（それが悪いという意味ではなく）ので、次回ちゃんと全体を見直さないといけないんじゃないかと。

現状も「関連する達成基準の実装方法一覧」で同じことが起きていて、これは以前から気になっているのですが。

**Comment by SawadaStdDesign** [comment]
（実は本音を言うと「いっそのこと両方取ってしまえばいいんじゃないか」と思っています。テストケースへのリンクを開くと同じ情報がありますので。）

**Comment by cocktailz** [comment]
澤田さんのおっしゃるように今回は情報設計などはやっていなくて、既存の枠組みの中でやっているので議論し始めると時間が必要な気がします。

とはいえ、もんどさんのご指摘も理解できるので、
ひとまず現時点で西本さんが修正してくださったように、各リンクの最後にAS情報へのリンクであることが分かるようにするというところでよいと思いマス。

ここまででテスト実施者への確認に進みたいと思います。
直前まで議論と修正作業ありがとうございます。

**Comment by SawadaStdDesign** [comment]
各リンクラベルに「に関連するAS情報」を付与し、公開済みのためcloseします。
